spring:
  application:
    name: wbrms-gateway
  cloud:
    gateway:
      routes:
        - id: billing-service
          uri: http://nrt.wbrms-menu-service.internal:8080/menu
          predicates:
            - Path=/menu/**
        - id: delivery-service
          uri: http://nrt.wbrms-food-delivery.internal:8080/food
          predicates:
            - Path=/food/**
management:
  endpoints:
    web:
      exposure:
        include: 'info, health'
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG