spring:
  application:
    name: wbrms-gateway
  cloud:
    gateway:
      routes:
        - id: billingService
          uri: http://sin.internal.wbrms-menu-service
          predicates:
            - Path=/menu/**